// Word list for random text generation
export const commonWords = [
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i',
  'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at',
  'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she',
  'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what',
  'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me',
  'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take',
  'people', 'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other',
  'than', 'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also',
  'back', 'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well', 'way',
  'even', 'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us',
  'is', 'water', 'long', 'find', 'here', 'thing', 'great', 'man', 'world', 'life',
  'still', 'public', 'human', 'read', 'keep', 'write', 'left', 'put', 'end', 'why',
  'while', 'mean', 'on', 'right', 'old', 'any', 'same', 'tell', 'boy', 'follow',
  'came', 'show', 'every', 'large', 'where', 'turn', 'ask', 'went', 'men', 'need',
  'land', 'different', 'home', 'move', 'try', 'kind', 'hand', 'picture', 'again', 'change',
  'off', 'play', 'spell', 'air', 'away', 'animal', 'house', 'point', 'page', 'letter',
  'mother', 'answer', 'found', 'study', 'learn', 'should', 'America', 'world', 'high', 'every',
  'near', 'add', 'food', 'between', 'own', 'below', 'country', 'plant', 'school', 'father',
  'never', 'start', 'city', 'earth', 'eye', 'light', 'thought', 'head', 'under', 'story',
  'saw', 'left', 'don\'t', 'few', 'while', 'along', 'might', 'close', 'something', 'seem',
  'next', 'hard', 'open', 'example', 'begin', 'life', 'always', 'those', 'both', 'paper',
  'together', 'got', 'group', 'often', 'run', 'important', 'until', 'children', 'side', 'feet',
  'car', 'mile', 'night', 'walk', 'white', 'sea', 'began', 'grow', 'took', 'river',
  'four', 'carry', 'state', 'once', 'book', 'hear', 'stop', 'without', 'second', 'later',
  'miss', 'idea', 'enough', 'eat', 'face', 'watch', 'far', 'Indian', 'really', 'almost',
  'let', 'above', 'girl', 'sometimes', 'mountain', 'cut', 'young', 'talk', 'soon', 'list',
  'song', 'being', 'leave', 'family', 'it\'s', 'body', 'music', 'color', 'stand', 'sun',
  'questions', 'fish', 'area', 'mark', 'dog', 'horse', 'birds', 'problem', 'complete', 'room',
  'knew', 'since', 'ever', 'piece', 'told', 'usually', 'didn\'t', 'friends', 'easy', 'heard',
  'order', 'red', 'door', 'sure', 'become', 'top', 'ship', 'across', 'today', 'during',
  'short', 'better', 'best', 'however', 'low', 'hours', 'black', 'products', 'happened', 'whole',
  'measure', 'remember', 'early', 'waves', 'reached', 'listen', 'wind', 'rock', 'space', 'covered',
  'fast', 'several', 'hold', 'himself', 'toward', 'five', 'step', 'morning', 'passed', 'vowel',
  'true', 'hundred', 'against', 'pattern', 'numeral', 'table', 'north', 'slowly', 'money', 'map',
  'farm', 'pulled', 'draw', 'voice', 'seen', 'cold', 'cried', 'plan', 'notice', 'south',
  'sing', 'war', 'ground', 'fall', 'king', 'town', 'I\'ll', 'unit', 'figure', 'certain',
  'field', 'travel', 'wood', 'fire', 'upon', 'done', 'English', 'road', 'half', 'ten',
  'fly', 'gave', 'box', 'finally', 'wait', 'correct', 'oh', 'quickly', 'person', 'became',
  'shown', 'minutes', 'strong', 'verb', 'stars', 'front', 'feel', 'fact', 'inches', 'street',
  'decided', 'contain', 'course', 'surface', 'produce', 'building', 'ocean', 'class', 'note', 'nothing',
  'rest', 'carefully', 'scientists', 'inside', 'wheels', 'stay', 'green', 'known', 'island', 'week',
  'less', 'machine', 'base', 'ago', 'stood', 'plane', 'system', 'behind', 'ran', 'round',
  'boat', 'game', 'force', 'brought', 'heat', 'nothing', 'quite', 'broke', 'case', 'middle',
  'kill', 'sons', 'lake', 'moment', 'scale', 'loud', 'spring', 'observe', 'child', 'straight',
  'consonant', 'nation', 'dictionary', 'milk', 'speed', 'method', 'organ', 'pay', 'age', 'section',
  'dress', 'cloud', 'surprise', 'quiet', 'stone', 'tiny', 'climb', 'bad', 'oil', 'blood',
  'touch', 'grew', 'cent', 'mix', 'team', 'wire', 'cost', 'lost', 'brown', 'wear',
  'garden', 'equal', 'sent', 'choose', 'fell', 'fit', 'flow', 'fair', 'bank', 'collect',
  'save', 'control', 'decimal', 'gentle', 'woman', 'captain', 'practice', 'separate', 'difficult', 'doctor',
  'please', 'protect', 'noon', 'whose', 'locate', 'ring', 'character', 'insect', 'caught', 'period',
  'indicate', 'radio', 'spoke', 'atom', 'human', 'history', 'effect', 'electric', 'expect', 'crop',
  'modern', 'element', 'hit', 'student', 'corner', 'party', 'supply', 'bone', 'rail', 'imagine',
  'provide', 'agree', 'thus', 'capital', 'won\'t', 'chair', 'danger', 'fruit', 'rich', 'thick',
  'soldier', 'process', 'operate', 'guess', 'necessary', 'sharp', 'wing', 'create', 'neighbor', 'wash',
  'bat', 'rather', 'crowd', 'corn', 'compare', 'poem', 'string', 'bell', 'depend', 'meat',
  'rub', 'tube', 'famous', 'dollar', 'stream', 'fear', 'sight', 'thin', 'triangle', 'planet',
  'hurry', 'chief', 'colony', 'clock', 'mine', 'tie', 'enter', 'major', 'fresh', 'search',
  'send', 'yellow', 'gun', 'allow', 'print', 'dead', 'spot', 'desert', 'suit', 'current',
  'lift', 'rose', 'continue', 'block', 'chart', 'hat', 'sell', 'success', 'company', 'subtract',
  'event', 'particular', 'deal', 'swim', 'term', 'opposite', 'wife', 'shoe', 'shoulder', 'spread',
  'arrange', 'camp', 'invent', 'cotton', 'born', 'determine', 'quart', 'nine', 'truck', 'noise',
  'level', 'chance', 'gather', 'shop', 'stretch', 'throw', 'shine', 'property', 'column', 'molecule',
  'select', 'wrong', 'gray', 'repeat', 'require', 'broad', 'prepare', 'salt', 'nose', 'plural',
  'anger', 'claim', 'continent', 'oxygen', 'sugar', 'death', 'pretty', 'skill', 'women', 'season',
  'solution', 'magnet', 'silver', 'thank', 'branch', 'match', 'suffix', 'especially', 'fig', 'afraid',
  'huge', 'sister', 'steel', 'discuss', 'forward', 'similar', 'guide', 'experience', 'score', 'apple',
  'bought', 'led', 'pitch', 'coat', 'mass', 'card', 'band', 'rope', 'slip', 'win',
  'dream', 'evening', 'condition', 'feed', 'tool', 'total', 'basic', 'smell', 'valley', 'nor',
  'double', 'seat', 'arrive', 'master', 'track', 'parent', 'shore', 'division', 'sheet', 'substance',
  'favor', 'connect', 'post', 'spend', 'chord', 'fat', 'glad', 'original', 'share', 'station',
  'dad', 'bread', 'charge', 'proper', 'bar', 'offer', 'segment', 'slave', 'duck', 'instant',
  'market', 'degree', 'populate', 'chick', 'dear', 'enemy', 'reply', 'drink', 'occur', 'support',
  'speech', 'nature', 'range', 'steam', 'motion', 'path', 'liquid', 'log', 'meant', 'quotient',
  'teeth', 'shell', 'neck'
];

// Predefined sentences and quotes for variety
export const sentences = [
  "The quick brown fox jumps over the lazy dog.",
  "A journey of a thousand miles begins with a single step.",
  "To be or not to be, that is the question.",
  "In the beginning was the Word, and the Word was with God.",
  "All that glitters is not gold, but it sure looks pretty.",
  "The only way to do great work is to love what you do.",
  "Life is what happens to you while you're busy making other plans.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It is during our darkest moments that we must focus to see the light.",
  "The way to get started is to quit talking and begin doing.",
  "Don't let yesterday take up too much of today.",
  "You learn more from failure than from success.",
  "If you are working on something that you really care about, you don't have to be pushed.",
  "Experience is the teacher of all things.",
  "The best time to plant a tree was twenty years ago. The second best time is now.",
  "Your limitation—it's only your imagination.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "What we think, we become.",
  "Be yourself; everyone else is already taken.",
  "Two things are infinite: the universe and human stupidity.",
  "So many books, so little time.",
  "A room without books is like a body without a soul.",
  "Be who you are and say what you feel, because those who mind don't matter.",
  "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  "You only live once, but if you do it right, once is enough.",
  "Be the change that you wish to see in the world.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "If you want to know what a man's like, take a good look at how he treats his inferiors.",
  "Don't walk in front of me… I may not follow. Don't walk behind me… I may not lead. Walk beside me… just be my friend.",
  "If you tell the truth, you don't have to remember anything.",
  "Friendship is born at that moment when one person says to another: What! You too? I thought I was the only one.",
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
  "A friend is someone who knows all about you and still loves you.",
  "To live is the rarest thing in the world. Most people just exist.",
  "That which does not kill us makes us stronger.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "We are all in the gutter, but some of us are looking at the stars.",
  "It is better to be hated for what you are than to be loved for what you are not.",
  "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.",
  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.",
  "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.",
  "Try not to become a person of success, but rather try to become a person of value.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "A woman is like a tea bag; you never know how strong it is until it's in hot water.",
  "A day without sunshine is like, you know, night.",
  "This world is but a canvas to our imagination.",
  "It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all.",
  "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
  "Logic will get you from A to B. Imagination will take you everywhere.",
  "There is no greater agony than bearing an untold story inside you.",
  "There is no friend as loyal as a book.",
  "It is never too late to be what you might have been.",
  "A classic is a book that has never finished saying what it has to say.",
  "You can never get a cup of tea large enough or a book long enough to suit me.",
  "Reading is essential for those who seek to rise above the ordinary.",
  "The person who reads too much and uses his brain too little will fall into lazy habits of thinking.",
  "A reader lives a thousand lives before he dies. The man who never reads lives only one.",
  "Books are a uniquely portable magic.",
  "The reading of all good books is like a conversation with the finest minds of past centuries.",
  "Think before you speak. Read before you think.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
  "A book is a dream that you hold in your hand.",
  "Words have no power to impress the mind without the exquisite horror of their reality.",
  "There is more treasure in books than in all the pirate's loot on Treasure Island.",
  "Reading is to the mind what exercise is to the body.",
  "A book is a version of the world. If you do not like it, ignore it or offer your own version in return.",
  "Once you learn to read, you will be forever free.",
  "Literacy is a bridge from misery to hope.",
  "Reading is a conversation. All books talk. But a good book listens as well.",
  "A great book should leave you with many experiences, and slightly exhausted at the end.",
  "Books fall open, you fall in, delighted where you've never been.",
  "Reading brings us unknown friends.",
  "Books are the plane, and the train, and the road. They are the destination, and the journey. They are home.",
  "I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.",
  "Books are mirrors: you only see in them what you already have inside you.",
  "If you don't like to read, you haven't found the right book.",
  "I do believe something very magical can happen when you read a good book.",
  "Reading is dreaming with open eyes.",
  "A book is a gift you can open again and again.",
  "Reading is an exercise in empathy; an exercise in walking in someone else's shoes for a while.",
  "Books are the quietest and most constant of friends; they are the most accessible and wisest of counselors.",
  "Reading is like thinking, like praying, like talking to a friend, like expressing your ideas, like listening to other people's ideas, like listening to music, like looking at the view, like taking a walk on the beach.",
  "The world belongs to those who read.",
  "Reading is the sole means by which we slip, involuntarily, often helplessly, into another's skin, another's voice, another's soul.",
  "Books are the carriers of civilization. Without books, history is silent, literature dumb, science crippled, thought and speculation at a standstill.",
  "A room without books is like a body without a soul.",
  "Reading is escape, and the opposite of escape; it's a way to make contact with reality after a day of making things up, and it's a way of making contact with someone else's imagination after a day that's all too real.",
  "Books can be dangerous. The best ones should be labeled 'This could change your life.'",
  "Reading is important, because if you can read, you can learn anything about everything and everything about anything.",
  "The man who does not read has no advantage over the man who cannot read.",
  "Today a reader, tomorrow a leader.",
  "Reading is a basic tool in the living of a good life.",
  "I cannot live without books.",
  "Reading gives us someplace to go when we have to stay where we are.",
  "Books are a form of political action. Books are knowledge. Books are reflection. Books change your mind.",
  "The reading of all good books is like conversation with the finest men of past centuries."
];

export default { commonWords, sentences };

